# Generated by Django 4.1.4 on 2023-05-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=200)),
                ('Auteur', models.CharField(max_length=200)),
                ('nom_du_fichier', models.CharField(max_length=200)),
                ('dernier_contributeur', models.CharField(max_length=200)),
                ('date_de_creation', models.DateField()),
                ('date_de_modification', models.DateField()),
                ('sujet', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
