# Generated by Django 4.2.2 on 2023-06-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='document',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='dernier_contributeur',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
