# Generated by Django 4.2.2 on 2023-06-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_fichier_document_alter_fichier_dernier_contributeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='document',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
